import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'ETC Live Checker Dashboard',
  description: 'Generated by jorbanicus',
}

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <head>
        {/* Include any head elements you need */}
      </head>
      <body className={inter.className}>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
};

export default RootLayout;